
name: Build Wheels (cibuildwheel)

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build_wheels:
    name: cibuildwheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.4
        env:
          CIBW_BUILD: cp310-* cp311-* cp312-* cp313-*
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: native
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_SKIP: pp* *-musllinux_* *i686 *win32
          CIBW_MANYLINUX_X86_64: manylinux2014
          CIBW_BEFORE_BUILD: >-
            python -m pip install -U pip setuptools wheel &&
            python -m pip install oldest-supported-numpy Cython cysignals
          CIBW_BEFORE_BUILD_MACOS: >-
            brew update &&
            brew install libomp &&
            python -m pip install -U pip setuptools wheel &&
            python -m pip install oldest-supported-numpy Cython cysignals
          CIBW_ENVIRONMENT: BLASTER_DEBUG=0
          CIBW_ENVIRONMENT_MACOS: |
            MACOSX_DEPLOYMENT_TARGET=15.0
          CIBW_TEST_COMMAND: >-
            python -c "import blaster, numpy as np; print('BLASter', blaster.__version__)"
        with:
          package-dir: .
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ runner.os }}
          path: wheelhouse/*.whl
          retention-days: 7

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build setuptools wheel

      - name: Build source distribution
        run: python -m build --sdist

      - name: Upload source distribution
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 7

  publish_test:
    name: Publish to TestPyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # Publish to TestPyPI on main branch pushes (for testing)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Download source distribution
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: List distributions to upload
        run: ls -la dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  publish:
      name: Publish to PyPI
      needs: [build_wheels, build_sdist]
      runs-on: ubuntu-latest
      # Only publish on tags (releases)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      steps:
        - name: Download wheels
          uses: actions/download-artifact@v4
          with:
            pattern: wheels-*
            path: dist
            merge-multiple: true

        - name: Download source distribution
          uses: actions/download-artifact@v4
          with:
            name: sdist
            path: dist

        - name: List distributions to upload
          run: ls -la dist/

        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@v1.13.0
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
