
name: Build Wheels (cibuildwheel)

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build_wheels:
    name: cibuildwheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.4
        env:
          CIBW_BUILD: cp311-* cp312-* cp313-*
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: native
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_SKIP: pp* *-musllinux_* *i686 *win32
          CIBW_MANYLINUX_X86_64: manylinux2014
          CIBW_BEFORE_BUILD: >-
            python -m pip install -U pip setuptools wheel &&
            python -m pip install oldest-supported-numpy Cython cysignals
          CIBW_BEFORE_BUILD_MACOS: >-
            brew update &&
            brew install llvm libomp &&
            python -m pip install -U pip setuptools wheel &&
            python -m pip install oldest-supported-numpy Cython cysignals &&
            mkdir -p $HOME/bin
            ln -sf /opt/homebrew/opt/llvm/bin/clang $HOME/bin/clang
            ln -sf /opt/homebrew/opt/llvm/bin/clang++ $HOME/bin/clang++
            export PATH=$HOME/bin:$PATH
          CIBW_ENVIRONMENT: BLASTER_DEBUG=0
          CIBW_ENVIRONMENT_MACOS: |
            MACOSX_DEPLOYMENT_TARGET=15.0
            CC=/usr/local/opt/llvm/bin/clang
            CXX=/usr/local/opt/llvm/bin/clang++
            CFLAGS="-I/usr/local/opt/libomp/include"
            CXXFLAGS="-I/opt/homebrew/opt/libomp/include -std=c++17 -Xpreprocessor -fopenmp -stdlib=libc++"
            LDFLAGS="-L/usr/local/opt/libomp/lib -lomp"
          CIBW_TEST_COMMAND: >-
            python -c "import blaster, numpy as np; print('BLASter', blaster.__version__)"
        with:
          package-dir: .
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ runner.os }}
          path: wheelhouse/*.whl
          retention-days: 7
